package controllers

import model.Section

object Sections {

  val sections = List(
    Section("FlnHno", 1),
    Section("HnoOrn", 1),
    Section("BlgOrn", 1),
    Section("BlgBlg", 999),
    Section("BlgSau", 1),
    Section("GtfSau", 1),
    Section("GtfSt", 1),
    Section("StSt", 999),
    Section("StVhy", 1),
    Section("HdmVhy", 1),
    Section("HdmHdm", 999),
    Section("HdmSnb", 1),
    Section("AvkySnb", 1),
    Section("AvkyAvky", 999),
    Section("AvkyRy", 1),
    Section("BdoRy", 1),
    Section("BdoSl", 1),
    Section("SlSl", 999),
    Section("IstSl", 1),
    Section("IstMå", 1),
    Section("JlaMå", 1),
    Section("BnaJla", 1),
    Section("BnaUna", 1),
    Section("UUna", 1),
    Section("UU", 999),
    Section("SäyU", 1),
    Section("EbySäy", 1),
    Section("EbyKn", 1),
    Section("KnMyn", 1),
    Section("ArncMyn", 1),
    Section("ArncArnc", 999),
    Section("ArncArne", 1),
    Section("ArneBvr", 1),
    Section("BvrSkby", 1),
    Section("SkbyUpv", 1),
    Section("RUpv", 1),
    Section("HgvR", 1),
    Section("HgvKmy", 1),
    Section("KmyUdl", 1),
    Section("TmöUdl", 1),
    Section("SoTmö", 1),
    Section("KeSo", 1),
    Section("CstKe", 1),
    Section("CstCst", 999),
    Section("KeTmö", 1),
    Section("SoUdl", 1)
  )
}
